### ISSUE TITLE
electron is being require in code, while not being listed in deps

### ISSUE THREAD

**Issue by iamstarkov** [soutar/hyperterm-register-shortcut#1]
im new to electron. but from nodejs development it seems wrong.
can you elaborate on how does this work?

**Comment by soutar** [comment]
Yeah, it does seem wrong when you look at package.json. Since this code runs in the context of a hyperterm plugin, the electron package is already available as it's installed as a dependency of hyperterm itself. Strictly speaking, this package should probably list electron as a peerDependency. Feel free to re-open in this if you think I haven't answered your question. 😄

**Comment by iamstarkov** [comment]
got it

**Comment by linonetwo** [comment]
But there is `Error: Electron failed to install correctly, please delete node_modules/electron and try installing again` run in hyper.
